#!/bin/bash

if [[ -n $(hyprctl -j workspaces | jq '.[].name | select(.=="special:dropdown")') ]]; then
	hyprctl dispatch togglespecialworkspace dropdown
else
	hyprctl dispatch -- exec [ workspace special:dropdown ] alacritty --class dropdown -e tmux new-session -As dropdown
	hyprctl dispatch togglespecialworkspace dropdown
fi
