#!/bin/bash

handle() {
	line=$1
	case $line in

	# move other windows out of dropdown workspace
	openwindow*)
		read -r window_address workspace window_class window_title <<<$(echo "$line" | awk -F "[>,]" '{print $3,$4,$5,$6}')
		if [[ "$workspace" = "special:dropdown" && "$window_class" != "dropdown" ]]; then
			hyprctl dispatch movetoworkspace e+0,address:0x${window_address}
			#hyprctl dispatch togglespecialworkspace dropdown
		fi
		if [[ "$window_title" = "Wine System Tray" ]]; then
			hyprctl dispatch closewindow address:0x${window_address}
		fi
		;;

	# move workspace to monitor when connected
	monitoradded*)
		monitor_name=$(echo "$line" | awk -F "[>,]" '{print $5}')
		if [[ "$monitor_name" = "HKC OVERSEAS LIMITED 27E1Q 0000000000001" ]]; then
			hyprctl dispatch moveworkspacetomonitor "6 desc:HKC OVERSEAS LIMITED 27E1Q 0000000000001"
			hyprctl dispatch moveworkspacetomonitor "7 desc:HKC OVERSEAS LIMITED 27E1Q 0000000000001"
			hyprctl dispatch moveworkspacetomonitor "8 desc:HKC OVERSEAS LIMITED 27E1Q 0000000000001"
			hyprctl dispatch moveworkspacetomonitor "9 desc:HKC OVERSEAS LIMITED 27E1Q 0000000000001"
			hyprctl dispatch moveworkspacetomonitor "10 desc:HKC OVERSEAS LIMITED 27E1Q 0000000000001"
		fi
		;;
	esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
