version = "1.1.3"

[class]
wechat = ""
"[Gg]oogle-chrome" = ""
"yuanshen.exe" = ""
"com.obsproject.Studio" = "󰕧"
code-oss = ""
gamescope = ""
"io.github.celluloid_player.Celluloid" = ""
"org.kde.kdeconnect.app" = ""
steam = "󰓓"
Pcmanfm = ""
font-manager = "󰬴"
"(?i)kitty" = ""
xfce4-terminal = ""
Motrix = ""
heroic = ""
chromium = ""
steam_proton = ""
libreoffice-calc = ""
xfreerdp = ""
"blueberry.py" = ""
"com.usebottles.bottles" = "󰡶"
fdm = ""
thunderbird = ""
thunar = ""
nemo = ""
virt-manager = ""
"org.kde.ark" = ""
selectdefaultapplication = ""
dconf-editor = ""
libreoffice-writer = ""
bottles = "󰡶"
looking-glass-client = ""
DEFAULT = "{delim}{class}"
"(?i)alacritty" = ""
microsoft-edge = "󰇩"
krita = ""
libreoffice-impress = ""
"org.kde.dolphin" = ""
qbittorrent = ""
"moe.launcher.an-anime-game-launcher" = ""
imv = ""
scrcpy = "󰀲"
nm-connection-editor = ""
rstudio = ""
"wechat.exe" = ""
"org.pwmt.zathura" = ""
"Free Download Manager" = ""
"org.telegram.desktop" = ""
Zotero = ""
"(?i)firefox" = ""

[class_active]
DEFAULT = "{class}"

[initial_class]

[initial_class_active]

[workspaces_name]
1 = "1"
2 = "2"
10 = "10"
12 = "12"
6 = "6"
0 = "0"
7 = "7"
8 = "8"
9 = "9"
3 = "3"
4 = "4"
11 = "11"
5 = "5"
[title_in_class.firefox]
"google.com" = ""
"github.com" = ""
"youtube.com" = "󰑈"
"bilibili.com" = "󰑈"
"reddit.com" = ""

[title_in_class."(?i)kitty"]
"(?i)nvim" = ""
"(?i)neomutt" = "neomutt"

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"[Ss]team" = "^$"
"(?i)fcitx" = ".*"
"(?i)TestApp" = ""
aProgram = "^$"

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}:{clients}{delim}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "{icon}"
client_active = "{icon}"
client_dup = "{client}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused}"
